# Project configuration
name: 'fda_dbt'
version: '1.0.0'

# The profile dbt will use for this project
profile: 'fda_dbt'

# Paths for dbt to find different types of files
model-paths: ["fda_dbt/models"]
macro-paths: ["fda_dbt/macros"]
analysis-paths: ["fda_dbt/analyses"]
test-paths: ["fda_dbt/tests"]
seed-paths: ["fda_dbt/seeds"]
snapshot-paths: ["fda_dbt/snapshots"]

# Directories to remove when running `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model configuration
models:
  fda_dbt:      # <--- YOU MUST HAVE THIS LINE FOR SCHEMAS TO WORK
    staging:
      +schema: "STAGING"
      +materialized: view

    clean:
      +schema: "CLEAN"
      +materialized: table

    marts:
      +schema: "MARTS"
      +materialized: table

    eda:
      +schema: "EDA"
      +materialized: table
