# Project configuration
name: 'fda_dbt'
version: '1.0.0'

# The profile dbt will use for this project
profile: 'fda_dbt'

# Paths for dbt to find different types of files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to remove when running `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model configuration
models:
  fda_dbt:
    # Staging models: raw data transformations
    staging:
      +schema: "STAGING"
      +materialized: view

    # Clean models: validated and normalized tables
    clean:
      +schema: "CLEAN"
      +materialized: table

    # Marts: dimensional models, facts and dims
    marts:
      +schema: "MARTS"
      +materialized: table
