name: 'fda_dbt'
version: '1.0.0'
config-version: 2
profile: 'fda_dbt'

# CLEAN PATHS: Only list these once.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# MODEL CONFIGS: Match your existing fda_dbt folder
models:
  fda_dbt:
    staging:
      +schema: STAGING
      +materialized: view
    clean:
      +schema: CLEAN
      +materialized: table
    marts:
      +schema: MARTS
      +materialized: table
    eda:
      +schema: EDA
      +materialized: table
